### ISSUE TITLE
Tensorflow and keras version

### ISSUE THREAD

**Issue by neeleshbisht99** [NyanCyanide/Lung-Segmentation#1]
Can you please share the Tensorflow and keras vesion you used, because I'm facing a issue like below: 

`{
	"name": "TypeError",
	"message": "Error when deserializing class 'Conv2DTranspose' using config={'name': 'conv2d_transpose', 'trainable': True, 'dtype': 'float32', 'filters': 128, 'kernel_size': [3, 3], 'strides': [2, 2], 'padding': 'same', 'data_format': 'channels_last', 'dilation_rate': [1, 1], 'groups': 1, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None, 'output_padding': None}.

Exception encountered: Unrecognized keyword arguments passed to Conv2DTranspose: {'groups': 1}",
	"stack": "---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/local_scratch/cmu_research/lib/python3.10/site-packages/keras/src/ops/operation.py:234, in Operation.from_config(cls, config)
    233 try:
--> 234     return cls(**config)
    235 except Exception as e:

File ~/local_scratch/cmu_research/lib/python3.10/site-packages/keras/src/layers/convolutional/conv2d_transpose.py:115, in Conv2DTranspose.__init__(self, filters, kernel_size, strides, padding, data_format, dilation_rate, activation, use_bias, kernel_initializer, bias_initializer, kernel_regularizer, bias_regularizer, activity_regularizer, kernel_constraint, bias_constraint, **kwargs)
     96 def __init__(
     97     self,
     98     filters,
   (...)
    113     **kwargs
    114 ):
--> 115     super().__init__(
    116         rank=2,
    117         filters=filters,
    118         kernel_size=kernel_size,
    119         strides=strides,
    120         padding=padding,
    121         data_format=data_format,
    122         dilation_rate=dilation_rate,
    123         activation=activation,
    124         use_bias=use_bias,
    125         kernel_initializer=kernel_initializer,
    126         bias_initializer=bias_initializer,
    127         kernel_regularizer=kernel_regularizer,
    128         bias_regularizer=bias_regularizer,
    129         activity_regularizer=activity_regularizer,
    130         kernel_constraint=kernel_constraint,
    131         bias_constraint=bias_constraint,
    132         **kwargs
    133     )

File ~/local_scratch/cmu_research/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv_transpose.py:94, in BaseConvTranspose.__init__(self, rank, filters, kernel_size, strides, padding, output_padding, data_format, dilation_rate, activation, use_bias, kernel_initializer, bias_initializer, kernel_regularizer, bias_regularizer, activity_regularizer, kernel_constraint, bias_constraint, trainable, name, **kwargs)
     71 def __init__(
     72     self,
     73     rank,
   (...)
     92     **kwargs,
     93 ):
---> 94     super().__init__(
     95         trainable=trainable,
     96         name=name,
     97         activity_regularizer=activity_regularizer,
     98         **kwargs,
     99     )
    100     self.rank = rank

File ~/local_scratch/cmu_research/lib/python3.10/site-packages/keras/src/layers/layer.py:266, in Layer.__init__(self, activity_regularizer, trainable, dtype, autocast, name, **kwargs)
    265 if kwargs:
--> 266     raise ValueError(
    267         \"Unrecognized keyword arguments \"
    268         f\"passed to {self.__class__.__name__}: {kwargs}\"
    269     )
    271 self._path = None  # Will be determined in `build_wrapper`

ValueError: Unrecognized keyword arguments passed to Conv2DTranspose: {'groups': 1}

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Cell In[20], line 2
      1 # Load the model
----> 2 model = load_model('./UNET_LungSegmentation_3D_10epochs_GPU_ALL.h5')

File ~/local_scratch/cmu_research/lib/python3.10/site-packages/keras/src/saving/saving_api.py:189, in load_model(filepath, custom_objects, compile, safe_mode)
    182     return saving_lib.load_model(
    183         filepath,
    184         custom_objects=custom_objects,
    185         compile=compile,
    186         safe_mode=safe_mode,
    187     )
    188 if str(filepath).endswith((\".h5\", \".hdf5\")):
--> 189     return legacy_h5_format.load_model_from_hdf5(
    190         filepath, custom_objects=custom_objects, compile=compile
    191     )
    192 elif str(filepath).endswith(\".keras\"):
    193     raise ValueError(
    194         f\"File not found: filepath={filepath}. \"
    195         \"Please ensure the file is an accessible `.keras` \"
    196         \"zip file.\"
    197     )

File ~/local_scratch/cmu_research/lib/python3.10/site-packages/keras/src/legacy/saving/legacy_h5_format.py:133, in load_model_from_hdf5(filepath, custom_objects, compile)
    130 model_config = json_utils.decode(model_config)
    132 with saving_options.keras_option_scope(use_legacy_config=True):
--> 133     model = saving_utils.model_from_config(
    134         model_config, custom_objects=custom_objects
    135     )
    137     # set weights
    138     load_weights_from_hdf5_group(f[\"model_weights\"], model)

File ~/local_scratch/cmu_research/lib/python3.10/site-packages/keras/src/legacy/saving/saving_utils.py:85, in model_from_config(config, custom_objects)
     81 # TODO(nkovela): Swap find and replace args during Keras 3.0 release
     82 # Replace keras refs with keras
     83 config = _find_replace_nested_dict(config, \"keras.\", \"keras.\")
---> 85 return serialization.deserialize_keras_object(
     86     config,
     87     module_objects=MODULE_OBJECTS.ALL_OBJECTS,
     88     custom_objects=custom_objects,
     89     printable_module_name=\"layer\",
     90 )

File ~/local_scratch/cmu_research/lib/python3.10/site-packages/keras/src/legacy/saving/serialization.py:495, in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    490 cls_config = _find_replace_nested_dict(
    491     cls_config, \"keras.\", \"keras.\"
    492 )
    494 if \"custom_objects\" in arg_spec.args:
--> 495     deserialized_obj = cls.from_config(
    496         cls_config,
    497         custom_objects={
    498             **object_registration.GLOBAL_CUSTOM_OBJECTS,
    499             **custom_objects,
    500         },
    501     )
    502 else:
    503     with object_registration.CustomObjectScope(custom_objects):

File ~/local_scratch/cmu_research/lib/python3.10/site-packages/keras/src/models/model.py:521, in Model.from_config(cls, config, custom_objects)
    516 if is_functional_config and revivable_as_functional:
    517     # Revive Functional model
    518     # (but not Functional subclasses with a custom __init__)
    519     from keras.src.models.functional import functional_from_config
--> 521     return functional_from_config(
    522         cls, config, custom_objects=custom_objects
    523     )
    525 # Either the model has a custom __init__, or the config
    526 # does not contain all the information necessary to
    527 # revive a Functional model. This happens when the user creates
   (...)
    530 # In this case, we fall back to provide all config into the
    531 # constructor of the class.
    532 try:

File ~/local_scratch/cmu_research/lib/python3.10/site-packages/keras/src/models/functional.py:477, in functional_from_config(cls, config, custom_objects)
    475 # First, we create all layers and enqueue nodes to be processed
    476 for layer_data in config[\"layers\"]:
--> 477     process_layer(layer_data)
    479 # Then we process nodes in order of layer depth.
    480 # Nodes that cannot yet be processed (if the inbound node
    481 # does not yet exist) are re-enqueued, and the process
    482 # is repeated until all nodes are processed.
    483 while unprocessed_nodes:

File ~/local_scratch/cmu_research/lib/python3.10/site-packages/keras/src/models/functional.py:457, in functional_from_config.<locals>.process_layer(layer_data)
    453 # Instantiate layer.
    454 if \"module\" not in layer_data:
    455     # Legacy format deserialization (no \"module\" key)
    456     # used for H5 and SavedModel formats
--> 457     layer = saving_utils.model_from_config(
    458         layer_data, custom_objects=custom_objects
    459     )
    460 else:
    461     layer = serialization_lib.deserialize_keras_object(
    462         layer_data, custom_objects=custom_objects
    463     )

File ~/local_scratch/cmu_research/lib/python3.10/site-packages/keras/src/legacy/saving/saving_utils.py:85, in model_from_config(config, custom_objects)
     81 # TODO(nkovela): Swap find and replace args during Keras 3.0 release
     82 # Replace keras refs with keras
     83 config = _find_replace_nested_dict(config, \"keras.\", \"keras.\")
---> 85 return serialization.deserialize_keras_object(
     86     config,
     87     module_objects=MODULE_OBJECTS.ALL_OBJECTS,
     88     custom_objects=custom_objects,
     89     printable_module_name=\"layer\",
     90 )

File ~/local_scratch/cmu_research/lib/python3.10/site-packages/keras/src/legacy/saving/serialization.py:504, in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    502     else:
    503         with object_registration.CustomObjectScope(custom_objects):
--> 504             deserialized_obj = cls.from_config(cls_config)
    505 else:
    506     # Then `cls` may be a function returning a class.
    507     # in this case by convention `config` holds
    508     # the kwargs of the function.
    509     custom_objects = custom_objects or {}

File ~/local_scratch/cmu_research/lib/python3.10/site-packages/keras/src/ops/operation.py:236, in Operation.from_config(cls, config)
    234     return cls(**config)
    235 except Exception as e:
--> 236     raise TypeError(
    237         f\"Error when deserializing class '{cls.__name__}' using \"
    238         f\"config={config}.\
\
Exception encountered: {e}\"
    239     )

TypeError: Error when deserializing class 'Conv2DTranspose' using config={'name': 'conv2d_transpose', 'trainable': True, 'dtype': 'float32', 'filters': 128, 'kernel_size': [3, 3], 'strides': [2, 2], 'padding': 'same', 'data_format': 'channels_last', 'dilation_rate': [1, 1], 'groups': 1, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None, 'output_padding': None}.

Exception encountered: Unrecognized keyword arguments passed to Conv2DTranspose: {'groups': 1}"
}`

**Comment by NyanCyanide** [comment]
While working on this code, I used the following versions:

TensorFlow: 2.15.0
Keras: 3.0.1

I believe these versions are relevant to the issue at hand. If you need any further information or have additional questions, please let me know.
